### ISSUE TITLE
Provide reference Java Client

### ISSUE THREAD

**Issue by jackdos** [JiscSD/rdss-par#30]
The PAR API should have a reference implementation of a Java client for interaction

**Comment by carlwilson** [comment]
Review and merge https://github.com/JiscRDSS/rdss-par/pull/40

@jackdos to provide a write up of what works and what doesn't.

**Comment by jackdos** [comment]
I have some offline test classes that test the various get methods in the api client. These appear to work against a local PAR API serving json that conforms to the schema version this commit is against.

Without a reliable public endpoint, or a test implementation of the endpoint to actually run these tests against, I don't really want to commit the tests. They do at least confirm that the JSON marshalling and HTTP connections work.

The local PAR API I have is running http and requires http basic auth connections, as far as I'm aware we've never stood up an API serve which served GET methods without some form of authentication, so that's the extent to which we can test it at this point I think.
